### ISSUE TITLE
Improve contrast between background and comments

### ISSUE THREAD

**Issue by MattAllison** [Tyriar/vscode-theme-sapphire#11]
Increase the contrast between the background color and the color of comments.  It's just a bit too difficult to read commented text.

**Comment by MattAllison** [comment]
Awesome timing.  Just got the update that included the new Dim and Light versions.  Dim is much better but slightly lighter coloring on the comment text itself may still help.  

The thing that made me open the issue is using comment-based help in PowerShell.

**Comment by Tyriar** [comment]
@MattAllison I'm open to lightening it a little more, it's very hard to see when selected.

Can you post a screenshot of the PowerShell comment-based help? I'm not familiar with this.

**Comment by MattAllison** [comment]
The image shows PowerShell comment help in normal, bright, and dim themes.

To reproduce, create a new PowerShell document and paste the text below.

![powershell comment help sapphire](https://cloud.githubusercontent.com/assets/6903342/25769649/2190bfcc-31d4-11e7-9114-fbb29833d716.png)

<#
.SYNOPSIS
    Short description
.DESCRIPTION
    Long description
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>

**Comment by Tyriar** [comment]
@MattAllison Thanks, I'll try lightening to #535a6b, any lighter and I'm concerned about it being too noisy.

**Comment by MattAllison** [comment]
Thanks!
