### ISSUE TITLE
Line/gutter highlight

### ISSUE THREAD

**Issue by alexkrolick** [Tyriar/vscode-theme-sapphire#12]
![image](https://user-images.githubusercontent.com/1571667/28224870-89eb9cd0-6885-11e7-9e26-a0d35889acc5.png)

At least for me, there is no highlighting for the current line in the text area or the gutter. It would be nice to have that feature.

**Comment by Tyriar** [comment]
After a quick look, I don't think this is supported in VS Code currently. I created https://github.com/Microsoft/vscode/issues/30727

**Comment by alexkrolick** [comment]
<img width="220" alt="screen shot 2017-07-14 at 12 04 29 pm" src="https://user-images.githubusercontent.com/1571667/28226908-a642dc02-688c-11e7-9fa7-787844751cda.png">

It is supported - there's a setting for it:

<img width="542" alt="screen shot 2017-07-14 at 12 05 38 pm" src="https://user-images.githubusercontent.com/1571667/28226944-c9cba71c-688c-11e7-8416-030c0116f3fc.png">

**Comment by Tyriar** [comment]
Ah, you learn something every day 😅 

In that case I recommend using `editor.lineHighlightBackground` and setting it to what you want for now:

```js
"workbench.colorCustomizations": {
  "editor.lineHighlightBackground": "#00F",
}
```

I'll move this issue to https://github.com/Tyriar/vscode-theme-generator/issues/42 to add support to the generator.
