### ISSUE TITLE
Publish a dark variant of Sapphire

### ISSUE THREAD

**Issue by vabatta** [Tyriar/vscode-theme-sapphire#4]
Hi,

good work! Finally a nice looking, clean and minimal theme! 
Just giving you a feedback, I find the background "too bright" and I moved the background from `#151B24` to `#1A1A1A` which is similar to the VS Code default gray.

Will follow and give more feedback!

P.s.: Also using some other extensions you made :P

**Comment by Tyriar** [comment]
Good feedback, I was actually originally thinking of making a "dark" variant which just darkens only the background color. I guess this confirms that people would want that :stuck_out_tongue: I'll probably look into doing this after the major issues with the theme are fixed to reduce rework.

I'd probably want to go with something more like `#0d1117` though to keep the blue hue:

![image](https://cloud.githubusercontent.com/assets/2193314/22576016/0a481ea4-e96e-11e6-859c-63f56bf896d3.png)

Please more feedback, particularly anything about missing or wrong colors, and great to hear you're using my extensions!
