### ISSUE TITLE
Markdown: Emphasis colors

### ISSUE THREAD

**Issue by gerane** [Tyriar/vscode-theme-sapphire#6]
Using emphasis produces results that are either very hard to see or have very little change. Most Code themes will give these alternate colors to make them easier to see. 

```markdown
Normal text *single asterisks* normal text
Normal text _single underscores_ normal text
Normal text **double asterisks** normal text
Normal text __double underscores__ normal text
Normal text **asterisks and _underscores_** normal text
```
Here is an image of how they currently look.

![2017-02-06_9-35-48](https://cloud.githubusercontent.com/assets/6662208/22653652/b1aebcc8-ec4f-11e6-93ae-9c46ddd0bec3.png)

Edit: Adding examples of other themes, but this is an area code themes have had issues, so many of them aren't totally right either. Markdown in VSCode was much better before version 1.3. Most of the markdown coloring in themes was broken during that update. They have fixed some of those issues, but many were only addressed in their own themes. 

Here is the default Dark+ theme

![2017-02-06_9-40-51](https://cloud.githubusercontent.com/assets/6662208/22653980/e38a3d48-ec50-11e6-9412-7054d17e0ec7.png)

Here is the default Monokai theme. Better, but would be better if they were separate colors.

![2017-02-06_9-50-18](https://cloud.githubusercontent.com/assets/6662208/22654244/ce22418e-ec51-11e6-8609-95e8b2ee4c06.png)

This is the Atom One Dark theme that is one of the defaults in Atom. Having different colors makes it much easier when editing markdown or reading it.

![2017-02-06_9-52-45](https://cloud.githubusercontent.com/assets/6662208/22654394/3af34d12-ec52-11e6-9b06-99272240a87f.png)

**Comment by Tyriar** [comment]
I was initially worried about coloring being too in your face but the light blue looks good!

Old:

![image](https://cloud.githubusercontent.com/assets/2193314/22659508/bb8b3eee-ec52-11e6-95ce-c06c6176b384.png)

New:

![image](https://cloud.githubusercontent.com/assets/2193314/22659529/cdd6fdc2-ec52-11e6-811a-d4db1e0d1de2.png)

**Comment by Tyriar** [comment]
@gerane I remembered why I decided against this initially; it can hide more important coloring inside. Notice the link doesn't stand out as much:

![image](https://cloud.githubusercontent.com/assets/2193314/23538073/52516a8e-ff85-11e6-8039-82ec42a94854.png)

**Comment by gerane** [comment]
What if you were to use a different link color?

**Comment by Tyriar** [comment]
That would work, trying to keep the palette small though so another color would probably clash elsewhere.
