### ISSUE TITLE
Markdown: Lists

### ISSUE THREAD

**Issue by gerane** [Tyriar/vscode-theme-sapphire#7]
Right now lists show up as white, and should have their bullets themed. This is broken in most themes. Code Version 1.3 broke these and now themes either don't color lists or color the line a solid color. Dark+ now handles these right after they edited the theme, but it left almost every other theme broken, so these usually have to be manually added.

```markdown
* Red
* Green
* Blue

- Red
- Green
- Blue

+ Red
+ Green
+ Blue

1. Bird
2. McHale
3. Parish
```

Here is how the theme currently colors a list.

![2017-02-06_10-02-20](https://cloud.githubusercontent.com/assets/6662208/22654736/5f7f5454-ec53-11e6-8221-5b46c2447f4d.png)

Here is how the Default theme Dark+ handles it

![2017-02-06_10-03-22](https://cloud.githubusercontent.com/assets/6662208/22654796/8c2289fe-ec53-11e6-8f66-daf355f4d0dd.png)

Here is the default Monokai theme.

![2017-02-06_10-04-23](https://cloud.githubusercontent.com/assets/6662208/22654849/b79234b8-ec53-11e6-91cf-aa4be234446c.png)
 
And for reference, this is how the Monokai theme handled lists before the 1.3 update. This is how the Atom Monokai theme handles lists which I believe is based on the same tmtheme, so this is likely the correct way the lists should be displayed.

![2017-02-06_10-05-38](https://cloud.githubusercontent.com/assets/6662208/22654911/ef7c0746-ec53-11e6-9795-608f609b020a.png)

**Comment by Tyriar** [comment]
👍 I think I'll make this blue to match the headings.
