### ISSUE TITLE
Apply the theme colours also to the rest of the UI

### ISSUE THREAD

**Issue by Narven** [Tyriar/vscode-theme-sapphire#9]
I like this theme,

but I really hate the difference between the editor colours and the rest of the UI.

Is it possible to apply the same coluor scheme to the rest of the UI?

thanks

**Comment by Tyriar** [comment]
Not until https://github.com/Microsoft/vscode/issues/3112 is done in VS Code, since it looks like it's coming soon I'll leave this open.

**Comment by Narven** [comment]
True I was reading this issue https://github.com/Microsoft/vscode/issues/1833 that seams to be related.

Thanks

**Comment by alexkrolick** [comment]
seems to be working!

**Comment by Tyriar** [comment]
Yep this is done, thanks for pointing it out @alexkrolick 👍
